In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim

2

In [5]:
a.shape

(2, 3)

In [6]:
b = np.arange(1,13)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
b.shape

(12,)

In [8]:
b.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
b.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
b.reshape(-1,2)

#-1 means we are asking numpy to calculate the number of rows needed

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
b.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
X.max(axis=1)

array([ 3,  7, 11])

In [20]:
X.sum()

66

In [21]:
X.T.max(axis=0) 

array([ 3,  7, 11])

In [22]:
[i.min() for i in X]

[0, 4, 8]

In [26]:
import numpy as np
arr = 2*np.arange(0,2,0.5)
if arr.all() <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 
    
arr

condition satisfies


array([0., 1., 2., 3.])

In [34]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])