In [1]:
import numpy as np
a = np.arange(1,25).reshape((2,3,4))
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [2]:
len(a)

2

In [3]:
a.ndim

3

In [4]:
a.shape

(2, 3, 4)

In [5]:
a.size

24

In [6]:
a.max(axis=0)

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [7]:
a.min(axis=1)

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [8]:
a.max(axis=2)

array([[ 4,  8, 12],
       [16, 20, 24]])

In [9]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
A = np.arange(9).reshape(3,3)

print(A[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [11]:
import numpy as np

A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [13]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
X.max(axis=1)

array([ 3,  7, 11])

In [15]:
X.sum()

66

In [16]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [17]:
[i.min() for i in X]

[0, 4, 8]

In [18]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [19]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [20]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [21]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 


1.0


In [22]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [23]:
X = np.arange(12).reshape((3,4))
row = np.array([0, 1, 2])
mask = np.array([1, 0, 1, 0], dtype=bool)
print(X[row[:, np.newaxis], mask])


[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [25]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [26]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [27]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [28]:
arr = np.arange(16).reshape(4,4)  

print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [29]:
arr = np.arange(10)
np.split(arr, 3)

ValueError: array split does not result in an equal division

In [ ]:
arr = np.arange(10)
np.split(arr, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [ ]:
arr = np.arange(10)
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int32)]

In [ ]:
arr = [[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]]
arr[1::] 

[[[9, 10, 11], [12, 13, 14], [15, 16, 17]]]

In [ ]:
arr = np.array([[[0, 1], 
             [2, 3]], 
 
            [[4, 5], 
             [6, 7]]])
arr[:, 0:,:1]

array([[[0],
        [2]],

       [[4],
        [6]]])

In [ ]:
A = np.arange(3)

B = np.arange(3, 7)

C = np.arange(7, 10)

D = np.concatenate([A, B, C])

print(D)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])
b = np.array([255, 0, 255])
c = np.all(a == b, axis = 1) 
c

array([[False,  True, False],
       [False, False, False]])