In [1]:
import numpy as np
a = [1,2,3,4,5]

b = [i**2 for i in a]
b

[1, 4, 9, 16, 25]

In [2]:
d = np.array([1,2,3,4,5])
d**2

array([ 1,  4,  9, 16, 25])

In [3]:
d+2

array([3, 4, 5, 6, 7])

In [4]:
d*2

array([ 2,  4,  6,  8, 10])

In [5]:
d*100

array([100, 200, 300, 400, 500])

In [6]:
np.arange(1000**2)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [7]:
d.shape

(5,)

In [8]:
d.shape[0]

5

In [9]:
d.ndim

1

In [10]:
c = np.arange(1,10,0.5)
c

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
type(d)

numpy.ndarray

In [12]:
d.dtype

dtype('int32')

In [13]:
e = np.array([1,2,True])
e

array([1, 2, 1])

In [14]:
f = np.array([1,2,3.0])
f

array([1., 2., 3.])

In [15]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])


A+"1"

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int32'), dtype('<U1')) -> None

In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1 
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [33]:
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a[5]

6

In [20]:
a[[5,3,7]]

array([6, 4, 8])

In [22]:
a[-6:-1:1]

array([4, 5, 6, 7, 8])

In [27]:
a[1:-2:2]

array([2, 4, 6])

In [30]:
a[6:-7:-3]

array([7, 4])

In [31]:
a[5::-2]

array([6, 4, 2])

In [34]:
a[:3:-3]

array([8, 5])

In [36]:
a[a<5]

array([1, 2, 3, 4])

In [40]:
a[a%2==0]

array([2, 4, 6, 8])

In [42]:
a[~(a%2==0)]

array([1, 3, 5, 7])

In [43]:
a[(a%2==0)|(a%5==0)]

array([2, 4, 5, 6, 8])

In [44]:
a[(a%2==0) & (a%3==0)]

array([6])

In [45]:
data = np.loadtxt("survey.txt")
data

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [47]:
total = len(data)
total

1167

In [49]:
promoters = data[data>8]

promoters_cnt = len(promoters)
promoters_cnt

609

In [51]:
detractors = data[data<6]

detractors_cnt = len(detractors)
detractors_cnt

332

In [55]:
nps = (promoters_cnt - detractors_cnt)
nps

277