In [1]:
import numpy as np
import pandas as pd

In [2]:
# a = np.array([13,25,31,14,43,35,78])

# ind = np.arange(a,)

In [3]:
np.arange(21,71,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69])

In [4]:
arr = [16,17,4,3,5,2]
res = []
for i in range(len(arr)-1):
    for j in range(i+1,len(arr)):
        if arr[i]<arr[j]:
            break
    else:
        res.append(arr[i])

res.append(arr[-1])
res

[17, 5, 2]

In [5]:
my_list = [123,456,789]
new_list = [sum(int(digit) for digit in str(num)) for num in my_list]

new_list

[6, 15, 24]

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [7]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [8]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [9]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [10]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [11]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(A[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [15]:
arr = np.array([[[ 0, 1, 2],
        [ 3, 4, 5], 
        [ 6, 7, 8]], 

        [[ 9, 10, 11], 
         [12, 13, 14], 
         [15, 16, 17]]])


arr[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [17]:
arr = np.array([[[0, 1], 
             [2, 3]], 
 
            [[4, 5], 
             [6, 7]]])

arr[:, 0:,:1]

array([[[0],
        [2]],

       [[4],
        [6]]])